Update to Forge 2705 as fix for startup crash java.lang.NoSuchMethodError in ItemCustomCompass.addPropertyOverride(ResourceLocation, IItemPropertyGetter)